name: Build Project Butler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: jackestar/esp8266-rtos-sdk-action@v1
        with:
          sdk-ref: 'master'
          install-deps: 'true'
          make-target: 'all'

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/*.bin

